name: Build and Deploy React App to ACR and Azure Container Apps üöÄ

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: grogu-front-end
  RESOURCE_GROUP: groguResourceGroup
  CONTAINER_APP_NAME: grogu-front-end
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: üîÑ Checkout code
        uses: actions/checkout@v3

      - name: üîê Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: üê≥ Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: üß± Build and push Docker image
        run: |
          docker build --no-cache -t $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: üì¶ Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          acrName: grogucr
